

<div class="pagetitle">
      <h1>SCO Voters</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="./">Home</a></li>
          <li class="breadcrumb-item">Utilities</li>
          <li class="breadcrumb-item active">SCO Voters</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section">

        <div class="row">
            <div class="col-sm-2">
                <input type="text" class="form-control" placeholder="School Year" id="sy">
            </div>
            <div class="col-sm-2">
                <button type="button" class="btn btn-primary rounded-pill mb-3" id="btn-setsy">Set School Year</button>
            </div>
        </div>    

      <div class="row">
        <div class="col-lg-12">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Voters Data</h5>
                <p>All the voters information is displayed and generated by this table.</p> 
                <!-- <button type="button" class="btn btn-success rounded-pill mb-3 float-end" id="btn-export">Export to CSV</button> -->
              <div class="dropdown">
                <button class="btn btn-success rounded-pill mb-3 float-end dropdown-toggle" type="button" id="btn-dropdown-export" data-bs-toggle="dropdown" aria-expanded="false">
                  Export Options
                </button>
                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="btn-dropdown-export">
                  <li><a class="dropdown-item" href="#" id="export-pdf">Export as PDF</a></li>
                  <li><a class="dropdown-item" href="#" id="export-csv">Export as CSV</a></li>
                  <li><a class="dropdown-item" href="#" id="export-csv-mysql">Export as CSV (MySQL)</a></li>
                </ul>
              </div>


              <!-- Table with stripped rows -->
              <table class="table datatable" id="tbl_voters">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Lastname</th>
                    <th>Firstname</th>
                    <th>Middlename</th>
                    <th>Level</th>
                    <th>Section</th>
                    <th>User</th>
                    <th>Pass</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  
                </tbody>
              </table>
              <!-- End Table with stripped rows -->

            </div>
          </div>

        </div>
      </div>
    </section>

<script src="../../assets/js/admin.utilities/scovoters.utils.js"></script>
<script src="../../assets/vendor/jspdf/jspdf.js"></script>

